In [1]:
import pandas as pd
df1 = pd.read_csv('PokemonData.csv')

In [2]:
df1

,Num,Name,Type1,Type2,HP,Attack,Defense,SpAtk,SpDef,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [3]:
df1.shape

(800, 12)

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Num         800 non-null    int64
 1   Name        800 non-null    str
 2   Type1       800 non-null    str
 3   Type2       414 non-null    str
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   SpAtk       800 non-null    int64
 8   SpDef       800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), str(3)
memory usage: 69.7 KB

In [5]:
df1.describe().round(2)

          Num      HP  Attack  Defense   SpAtk   SpDef   Speed  Generation
count  800.00  800.00  800.00   800.00  800.00  800.00  800.00      800.00
mean   362.81   69.26   79.00    73.84   72.82   71.90   68.28        3.32
std    208.34   25.53   32.46    31.18   32.72   27.83   29.06        1.66
min      1.00    1.00    5.00     5.00   10.00   20.00    5.00        1.00
25%    184.75   50.00   55.00    50.00   49.75   50.00   45.00        2.00
50%    364.50   65.00   75.00    70.00   65.00   70.00   65.00        3.00
75%    539.25   80.00  100.00    90.00   95.00   90.00   90.00        5.00
max    721.00  255.00  190.00   230.00  194.00  230.00  180.00        6.00

In [6]:
df1["Type1"].unique()

<StringArray>
[   'Grass',     'Fire',    'Water',      'Bug',   'Normal',   'Poison',
 'Electric',   'Ground',    'Fairy', 'Fighting',  'Psychic',     'Rock',
    'Ghost',      'Ice',   'Dragon',     'Dark',    'Steel',   'Flying']
Length: 18, dtype: str

In [9]:
df1["Type1"].value_counts()

Type1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Ground       32
Ghost        32
Dragon       32
Dark         31
Poison       28
Fighting     27
Steel        27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

In [7]:
df1["Type2"].unique()

<StringArray>
[  'Poison',        nan,   'Flying',   'Dragon',   'Ground',    'Fairy',
    'Grass', 'Fighting',  'Psychic',    'Steel',      'Ice',     'Rock',
     'Dark',    'Water', 'Electric',     'Fire',    'Ghost',      'Bug',
   'Normal']
Length: 19, dtype: str

In [10]:
df1["Type2"].value_counts()

Type2
Flying      97
Ground      35
Poison      34
Psychic     33
Fighting    26
Grass       25
Fairy       23
Steel       22
Dark        20
Dragon      18
Ice         14
Rock        14
Water       14
Ghost       14
Fire        12
Electric     6
Normal       4
Bug          3
Name: count, dtype: int64

In [8]:
df1["Generation"].unique()

array([1, 2, 3, 4, 5, 6])

In [11]:
df1["Generation"].value_counts()

Generation
1    166
5    165
3    160
4    121
2    106
6     82
Name: count, dtype: int64

Este dataset tiene 800 filas y 12 columnas
Las columnas Name, Type1 y Type2 son de tipo str, la columna Legendary es de tipo bool y el resto de columnas son de tipo int64

La columna Type1 tiene un total de 18 elementos unicos y son los tipos que existen en pokemon
La columna Type2 tiene un total de 19 elementos unicos uno mas que el Type1 debido a que existen pokemons con un unico tipo
La columna Generation tiene un total de 6 elementos unicos, un numero por generacion de juego
La columna Num contiene el numero de pokedex de ese pokemon pero no es unico por pokemon porque existen variantes de pokemons que usan el mismo numero de registro

Columnas HP, Attack, Defense, SpAtk, SpDef, Speed
La media y la mediana nos indica que la mayoria de datos estan sesgados hacia valores altos
La desviacion standar indica que las estadísticas ofensivas varían más que las defensivas

Tipo de variables:
Numerica continua: HP, Attack, Defense, SpAtk, SpDef, Speed
Categorica nominal: Num, Name, Type1, Type2
Categorica ordinal: Generation